from typing import Literal

KeyboardKey = (
    Literal[
        # Letter keys
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        # Number keys
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        # Symbol keys
        "-",
        "=",
        "[",
        "]",
        "\\",
        ";",
        "'",
        ",",
        ".",
        "/",
        "`",
        # Modifier keys
        "shift",
        "ctrl",
        "alt",
        "command",
        "option",
        # Control keys
        "enter",
        "return",
        "esc",
        "escape",
        "tab",
        "backspace",
        "delete",
        "space",
        # Arrow keys
        "up",
        "down",
        "left",
        "right",
        # Function keys
        "f1",
        "f2",
        "f3",
        "f4",
        "f5",
        "f6",
        "f7",
        "f8",
        "f9",
        "f10",
        "f11",
        "f12",
        # Other keys
        "home",
        "end",
        "pageup",
        "pagedown",
        "insert",
        "printscreen",
        "capslock",
        "numlock",
        "scrolllock",
        "pause",
    ]
    | str
)
