from pathlib import Path

import rich_click as click

from kiari.core.paths import (
    get_config_file_path,
    get_profile_config_file_path,
    get_profile_run_spec_file_path,
)
from kiari.core.profile import profile_store
from kiari.core.rich import console_registry, render_status_block


@click.command(
    short_help="Create the shared config file used by all profiles.",
    help=(
        "Create the shared configuration file for `kiari` if it does not exist yet.\n\n"
        "This file stores settings shared across all profiles, such as common app-level "
        "configuration. Existing files are kept as-is."
    ),
)
def init() -> None:  # pragma: no cover
    """Initialize the shared config file used by every profile."""
    _init()


def _init() -> None:
    file_path = get_config_file_path()
    profile_name = "default"
    run_spec_file_path = get_profile_run_spec_file_path(profile_name)
    profile_config_file_path = get_profile_config_file_path(profile_name)
    created_shared_config = _ensure_shared_config(file_path)
    created_run_spec = profile_store.ensure_run_spec(profile_name)
    created_config = profile_store.ensure_config(profile_name)
    console_registry.get().print(
        render_status_block(
            title="Initialization completed.",
            lines=[
                (
                    f"Global config: created [dim]{file_path}[/dim]"
                    if created_shared_config
                    else f"Global config: already exists [dim]{file_path}[/dim]"
                ),
                (
                    f"Default profile RunSpec: created [dim]{run_spec_file_path}[/dim]"
                    if created_run_spec
                    else f"Default profile RunSpec: already exists [dim]{run_spec_file_path}[/dim]"
                ),
                (
                    f"Default profile config: created [dim]{profile_config_file_path}[/dim]"
                    if created_config
                    else f"Default profile config: already exists [dim]{profile_config_file_path}[/dim]"
                ),
            ],
            status="success",
        )
    )


def _ensure_shared_config(file_path: Path) -> bool:
    if file_path.exists():
        return False

    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(_get_config_template())
    return True


def _get_config_template() -> str:
    return """# Kiari2 Shared Configuration File
# This file is automatically generated by `kiari admin init`
#
# This file stores settings shared by all profiles.
# Profile-specific settings should be managed separately in profiles.yaml.
"""
