STREAMLIT_STARTUP_FILE_ENV_VAR = "KIARI_STREAMLIT_STARTUP_FILE"
STREAMLIT_BROWSER_USER_ID_KEY = "kiari_browser_user_id"
STREAMLIT_SELECTED_AGENT_ID_KEY = "kiari_selected_agent_id"
STREAMLIT_SESSION_KEY = "kiari_streamlit_session"
